name: CI/CD Pipeline for Sample API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry Dependency Manager
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: poetry install --no-root

      - name: Execute Unit Tests
        run: ./run-unit-tests.sh

  build-and-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Build and Deploy Docker Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sample-api:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
